### ISSUE TITLE
MissingTokenError: (missing_token) Missing access token parameter.

### ISSUE THREAD

**Issue by nkirsch** [bwilczynski/strava-cli#7]
Ran `config` && `login`.

After hitting `Authorize` on the Strava web form - which displayed my app - I received this traceback:

```
# 12:30 % strava login
Traceback (most recent call last):
  File "/usr/local/bin/strava", line 11, in <module>
    load_entry_point('strava-cli==0.4.9', 'console_scripts', 'strava')()
  File "/usr/local/Cellar/strava-cli/0.4.9/libexec/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/strava-cli/0.4.9/libexec/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/strava-cli/0.4.9/libexec/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/strava-cli/0.4.9/libexec/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/strava-cli/0.4.9/libexec/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/strava-cli/0.4.9/libexec/lib/python3.7/site-packages/strava/decorators.py", line 86, in wrapper_config_required
    return func(*args, **kwargs)
  File "/usr/local/Cellar/strava-cli/0.4.9/libexec/lib/python3.7/site-packages/strava/commands/login.py", line 20, in login
    data = auth_flow.get_access_token(code)
  File "/usr/local/Cellar/strava-cli/0.4.9/libexec/lib/python3.7/site-packages/strava/api/oauth2.py", line 64, in get_access_token
    client_secret=self.client_secret)
  File "/usr/local/Cellar/strava-cli/0.4.9/libexec/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 360, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/Cellar/strava-cli/0.4.9/libexec/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/Cellar/strava-cli/0.4.9/libexec/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/Cellar/strava-cli/0.4.9/libexec/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.
```

**Comment by Andy-Dawes** [comment]
I have the same issue - with the same traceback message

**Comment by bwilczynski** [comment]
It should now be solved, simply update: `brew update && brew upgrade strava-cli` if you're using Homebrew or update version from PyPi to 0.4.10
